[project]
name = "gerador-de-exercicios-matematicos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pylatex>=1.4.2",
]
